--Lab 5 1
CREATE VIEW  LAB5_Credit
AS
SELECT STDID, STDFNAME, STDLNAME, SUM(CREDIT) TotalCredit
FROM(
    SELECT STU.STDID, STU.STDFNAME, STU.STDLNAME, SUB.CREDIT
    FROM STUDENT STU
        INNER JOIN REGISTER REG ON REG.STDID = STU.STDID
        INNER JOIN SUBJECT SUB ON SUB.SUBJCODE = REG.SUBJCODE)
GROUP BY STDID, STDFNAME, STDLNAME
ORDER BY STDID;

--Lab 5 2
CREATE VIEW  LAB5_RegFee
AS
SELECT STDID, STDFNAME, STDLNAME, YEAR, SEMESTER, SUM(CREDIT) TotalCredit, SUM(CREDIT) * 1000 REGFEE
FROM(
    SELECT STU.STDID, STU.STDFNAME, STU.STDLNAME, REG.YEAR, REG.SEMESTER, SUB.CREDIT
    FROM STUDENT STU
        INNER JOIN REGISTER REG ON REG.STDID = STU.STDID
        INNER JOIN SUBJECT SUB ON SUB.SUBJCODE = REG.SUBJCODE)
GROUP BY STDID, STDFNAME, STDLNAME, YEAR, SEMESTER
ORDER BY STDID;

--Lab 5 3
CREATE VIEW  LAB5_GPA
AS
SELECT STDID, STDFNAME, STDLNAME, SUM( CREDIT * GRADE) / SUM(CREDIT) GPA
FROM(
    SELECT STU.STDID, STU.STDFNAME, STU.STDLNAME, SUB.CREDIT, REG.GRADE
    FROM STUDENT STU
        INNER JOIN REGISTER REG ON REG.STDID = STU.STDID
        INNER JOIN SUBJECT SUB ON SUB.SUBJCODE = REG.SUBJCODE)
GROUP BY STDID, STDFNAME, STDLNAME
ORDER BY GPA;

--LAB 5 4 เพิ่มข้อมูลนักศึกษา
INSERT INTO STUDENT (STDID, STDFNAME, STDLNAME, STDADDRESS, FCODE, DCODE, TCODE)
VALUES('563020197-5', 'กฤษดา',  'โสมายัง', '123 จ.ขอนแก่น', 'F01', 'D03', 'T01');

INSERT INTO STUDENT (STDID, STDFNAME, STDLNAME, STDADDRESS, FCODE, DCODE, TCODE)
VALUES('563020200-2', 'ขวัญข้าว',  'เสียงเลิศ', '11 จ.ขอนแก่น', 'F01', 'D03', NULL);

INSERT INTO STUDENT (STDID, STDFNAME, STDLNAME, STDADDRESS, FCODE, DCODE, TCODE)
VALUES('563020205-2', 'ชนนิกา', 'ปัญจันทร์สิงห', '15 จ.ขอนแก่น', 'F01', 'D03', NULL);

INSERT INTO STUDENT (STDID, STDFNAME, STDLNAME, STDADDRESS, FCODE, DCODE, TCODE)
VALUES('563020206-0', 'ชนัญชิดา',  'อินทะสร้อย', '16 จ.ขอนแก่น', 'F01', 'D03', NULL);

--LAB 5 5

CREATE VIEW  LAB5_GPA_Outer
AS
SELECT STDID, STDFNAME, STDLNAME, SUM( CREDIT * GRADE) / SUM(CREDIT) GPA
FROM(
    SELECT STU.STDID, STU.STDFNAME, STU.STDLNAME, SUB.CREDIT, REG.GRADE
    FROM STUDENT STU
        LEFT OUTER JOIN REGISTER REG ON REG.STDID = STU.STDID
        LEFT OUTER JOIN SUBJECT SUB ON SUB.SUBJCODE = REG.SUBJCODE)
GROUP BY STDID, STDFNAME, STDLNAME
ORDER BY GPA;

--LAB 5 6
CREATE VIEW  LAB5_Teacher_Outer
AS
SELECT STDID, STDFNAME, STDLNAME, TCODE , TFNAME, TLNAME
FROM(
    SELECT STU.STDID, STU.STDFNAME, STU.STDLNAME, T.TCODE, T.TFNAME, T.TLNAME
    FROM STUDENT STU
        LEFT OUTER JOIN TEACHER T ON T.TCODE = STU.TCODE
    )
ORDER BY TCODE;

