INSERT INTO STUDENT (STDID, STDFNAME, STDLNAME, STDADDRESS, FCODE, DCODE, TCODE) 
VALUES('563020197-5', 'กฤษดา',  'โสมายัง', '123 จ.ขอนแก่น', 'F01', 'D03', 'T01');

INSERT INTO STUDENT (STDID, STDFNAME, STDLNAME, STDADDRESS, FCODE, DCODE, TCODE) 
VALUES('563020200-2', 'ขวัญข้าว',  'เสียงเลิศ', '11 จ.ขอนแก่น', 'F01', 'D03', NULL);

INSERT INTO STUDENT (STDID, STDFNAME, STDLNAME, STDADDRESS, FCODE, DCODE, TCODE) 
VALUES('563020205-2', 'ชนนิกา',  'ปัญจันทร์สิงห์', '15 จ.ขอนแก่น', 'F01', 'D03', NULL);

INSERT INTO STUDENT (STDID, STDFNAME, STDLNAME, STDADDRESS, FCODE, DCODE, TCODE) 
VALUES('563020206-0', 'ชนัญชิดา',  'อินทะสร้อย', '16 จ.ขอนแก่น', 'F01', 'D03', NULL);

